base_images:
  cli:
    name: "4.11"
    namespace: ocp
    tag: cli
  operator-base:
    name: ubi
    namespace: ocp
    tag: "8"
binary_build_commands: make build
build_root:
  image_stream_tag:
    name: builder
    namespace: ocp
    tag: rhel-8-golang-1.18-openshift-4.11
images:
- dockerfile_path: Dockerfile
  from: operator-base
  to: self-node-remediation-operator
- dockerfile_literal: |
    FROM src
    COPY oc /usr/bin/oc
  from: src
  inputs:
    cli:
      paths:
      - destination_dir: .
        source_path: /usr/bin/oc
  to: src-oc
operator:
  bundles:
  - as: self-node-remediation-bundle
    dockerfile_path: bundle.Dockerfile
  substitutions:
  - pullspec: quay.io/medik8s/self-node-remediation-operator:.*
    with: pipeline:self-node-remediation-operator
releases:
  latest:
    candidate:
      product: ocp
      stream: nightly
      version: "4.11"
resources:
  '*':
    requests:
      cpu: 500m
      memory: 1000Mi
test_binary_build_commands: make test
tests:
- as: test
  commands: make test
  container:
    from: src
  skip_if_only_changed: ^docs/|\.md$|^(?:.*/)?(?:\.gitignore|OWNERS|PROJECT|LICENSE)$
- as: e2e-test
  skip_if_only_changed: ^docs/|\.md$|^(?:.*/)?(?:\.gitignore|OWNERS|PROJECT|LICENSE)$
  steps:
    cluster_claim:
      # architecture, cloud, owner, product, and version are used to determine a cluster pool by matching the labels
      as: custom    # optional; release name to use when importing cluster claim release; defaults to `latest`
      architecture: amd64
      cloud: aws
      owner: openshift-ci
      product: ocp
      timeout: 1h0m0s
      version: "4.11"
      labels: # optional; more labels to match besides architecture, cloud, owner, product, and version defined above
        size: "6"
    dependencies:
      OO_INDEX: ci-index-self-node-remediation-bundle
    env:
      OO_CHANNEL: stable
      OO_INSTALL_NAMESPACE: self-node-remediation
      OO_PACKAGE: self-node-remediation
      OO_TARGET_NAMESPACES: '!all'
    test:
    - as: e2e
      commands: make e2e-test
      from: src-oc
      resources:
        requests:
          cpu: 100m
          memory: 200Mi
    workflow: optional-operators-ci-aws
zz_generated_metadata:
  branch: main
  org: medik8s
  repo: self-node-remediation
